
spring:
  thymeleaf:
    cache: false
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

application:
  mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/menuMapper.xml
    type-aliases-package: kr.ac.cnu.web.model

server:
 port: 9000
